### ISSUE TITLE
Add addtional not_*() functions

### ISSUE THREAD

**Issue by nthallen** [nthallen/le-dasng#4]
Look in Zeno, any other drivers out there.

**Comment by nthallen** [comment]
Not all of these apply, but most:

Zeno_UDP.cc: `int Zeno_UDP::not_ndigits(int n, int &value)`
Zeno_UDP.cc: `int Zeno_UDP::not_zeno_time(double &Time)`
Zeno_UDP.cc: `int Zeno_UDP::not_ushort(unsigned short &val)`
Zeno_UDP.cc: `int Zeno_UDP::not_fix(int fix, signed short &val)`
Zeno_UDP.cc: `int Zeno_UDP::not_hex( unsigned long &hexval )`

**Comment by nthallen** [comment]
When importing code from old projects, we want to:

- Change return from `int` to `bool`
- Replace `return 0` with `return false` and `return 1` with `return true`
- Replace any `long` or `short` types with stdint.h types, e.g. `uint16_t`
- Update/create documentation in dasio.h
- Add tests for each method

**Comment by nthallen** [comment]
- `bool not_word()` How should this work?

**Comment by nthallen** [comment]
For tests, be sure to include tests of leading whitespace, negative values. Also tests where a syntax error occurs in the middle of the input string. e.g. not_int() with an input string like "  -K". Verify failure and the cp position where the failure occurs.

**Comment by M-E-A** [comment]
> * `bool not_word()` How should this work?

If we're talking a word in the traditional sense, then we would want to check each character to see if it contained any numerals or punctuation maybe? If yes, then false, if no (if it's only letters), then true. Perhaps?

**Comment by nthallen** [comment]
I decided the `not_word()` was a little too application-specific to put into DAS_IO::Interface, just put it directly into DAS_IO::Authenticator (which might become DAS_IO::Server::Authenticator) along with a `not_svc()` function.
