### ISSUE TITLE
Resolve msg_hdr_default

### ISSUE THREAD

**Issue by M-E-A** [nthallen/le-dasng#44]
Figure out what to do about
`const char *msg_hdr_default;`
In lgr.oui, tm_client.oui, etc.

**Comment by nthallen** [comment]
- Rename this to appid_default
- Include default AppID definitions for clt, srvr, disp, col, etc.
- Create no_appid package to inhibit the appid_default (i.e. provide an empty appid_default package)
- Implement or replace/rename the following (including references in appgen)
  - /usr/local/share/oui/cis.oui
  - /usr/local/share/oui/collect.oui
  - /usr/local/share/oui/kbdclt.oui
  - /usr/local/share/oui/seteuid.oui
